version: "3"
services:
  restapi:
    image: 4039497ddfe7
    ports:
      - "8080:8080"
    networks:
      - mariadb-nw
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    networks:
      - mariadb-nw
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=myDB

networks:
  mariadb-nw:
